# Generated by Django 4.1.5 on 2023-01-28 15:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Members",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200)),
                ("email", models.CharField(max_length=200)),
                ("password", models.EmailField(max_length=200)),
                ("age", models.CharField(max_length=200)),
                ("balance", models.IntegerField()),
            ],
        ),
    ]
